/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.kodfarki.subscreasy.client.model


/**
 * 
 * @param city 
 * @param country 
 * @param id 
 * @param name 
 * @param postalCode 
 * @param stateProvince 
 * @param streetAddress 
 */
data class Address (
    val city: kotlin.String? = null,
    val country: kotlin.String? = null,
    val id: kotlin.Long? = null,
    val name: kotlin.String? = null,
    val postalCode: kotlin.String? = null,
    val stateProvince: kotlin.String? = null,
    val streetAddress: kotlin.String? = null
) {

}

