/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.kodfarki.subscreasy.client.model


/**
 * 
 * @param serviceId 
 * @param serviceUserId 
 */
data class Authorization (
    val serviceId: kotlin.Long? = null,
    val serviceUserId: kotlin.String? = null
) {

}

