/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.kodfarki.subscreasy.client.model

import com.kodfarki.subscreasy.client.model.Company

/**
 * 
 * @param branch 
 * @param city 
 * @param company 
 * @param country 
 * @param iban 
 * @param id 
 * @param name 
 */
data class BankAccount (
    val iban: kotlin.String,
    val name: kotlin.String,
    val branch: kotlin.String? = null,
    val city: kotlin.String? = null,
    val company: Company? = null,
    val country: kotlin.String? = null,
    val id: kotlin.Long? = null
) {

}

