/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.kodfarki.subscreasy.client.model


/**
 * 
 * @param cancellationType 
 * @param subscriptionId 
 */
data class Cancellation (
    val cancellationType: Cancellation.CancellationType? = null,
    val subscriptionId: kotlin.Long? = null
) {

    /**
    * 
    * Values: iMMEDIATE,eNDOFTHEPERIOD
    */
    enum class CancellationType(val value: kotlin.Any){
    
        iMMEDIATE("IMMEDIATE"),
    
        eNDOFTHEPERIOD("ENDOFTHEPERIOD");
    
    }

}

