/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.kodfarki.subscreasy.client.model

import com.kodfarki.subscreasy.client.model.Address

/**
 * 
 * @param address 
 * @param id 
 * @param name 
 * @param siteName 
 */
data class Company (
    val name: kotlin.String,
    val address: Address? = null,
    val id: kotlin.Long? = null,
    val siteName: kotlin.String? = null
) {

}

