/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.kodfarki.subscreasy.client.model

import com.kodfarki.subscreasy.client.model.Company

/**
 * 
 * @param apiKey 
 * @param callbackUrl 
 * @param company 
 * @param id 
 * @param paymentGatewayApiKey 
 * @param paymentGatewaySecurityKey 
 * @param paymentMethod 
 * @param secureKey 
 */
data class CompanyProps (
    val apiKey: kotlin.String? = null,
    val callbackUrl: kotlin.String? = null,
    val company: Company? = null,
    val id: kotlin.Long? = null,
    val paymentGatewayApiKey: kotlin.String? = null,
    val paymentGatewaySecurityKey: kotlin.String? = null,
    val paymentMethod: CompanyProps.PaymentMethod? = null,
    val secureKey: kotlin.String? = null
) {

    /**
    * 
    * Values: oFFLINE,iYZICO,pAYU
    */
    enum class PaymentMethod(val value: kotlin.Any){
    
        oFFLINE("OFFLINE"),
    
        iYZICO("IYZICO"),
    
        pAYU("PAYU");
    
    }

}

