/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.kodfarki.subscreasy.client.model

import com.kodfarki.subscreasy.client.model.Company

/**
 * 
 * @param code 
 * @param company 
 * @param currentUsage 
 * @param discountAmount 
 * @param discountType 
 * @param expireDate 
 * @param id 
 * @param maxLimit 
 */
data class Coupon (
    val discountAmount: java.math.BigDecimal,
    val discountType: Coupon.DiscountType,
    val maxLimit: kotlin.Int,
    val code: kotlin.String? = null,
    val company: Company? = null,
    val currentUsage: kotlin.Int? = null,
    val expireDate: java.time.LocalDateTime? = null,
    val id: kotlin.Long? = null
) {

    /**
    * 
    * Values: fIXED,pERCENTAGE
    */
    enum class DiscountType(val value: kotlin.Any){
    
        fIXED("FIXED"),
    
        pERCENTAGE("PERCENTAGE");
    
    }

}

