/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.kodfarki.subscreasy.client.model

import com.kodfarki.subscreasy.client.model.Order
import com.kodfarki.subscreasy.client.model.PaymentCard

/**
 * 
 * @param order 
 * @param paymentCard 
 */
data class CreateOrderRequest (
    val order: Order? = null,
    val paymentCard: PaymentCard? = null
) {

}

