/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.kodfarki.subscreasy.client.model


/**
 * 
 * @param capacity 
 * @param consumedResourceId 
 * @param overUsage 
 * @param requestedAmount 
 * @param subscriptionId 
 * @param usage 
 */
data class DeductionResult (
    val capacity: java.math.BigDecimal? = null,
    val consumedResourceId: kotlin.Long? = null,
    val overUsage: java.math.BigDecimal? = null,
    val requestedAmount: kotlin.Long? = null,
    val subscriptionId: kotlin.Long? = null,
    val usage: java.math.BigDecimal? = null
) {

}

