/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.kodfarki.subscreasy.client.model


/**
 * 
 * @param amount 
 * @param id 
 * @param serviceId 
 * @param usageEndTime 
 * @param usageStartTime 
 * @param userId 
 */
data class Deduction (
    val amount: kotlin.Long? = null,
    val id: kotlin.Long? = null,
    val serviceId: kotlin.Long? = null,
    val usageEndTime: java.time.LocalDateTime? = null,
    val usageStartTime: java.time.LocalDateTime? = null,
    val userId: kotlin.String? = null
) {

}

