/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.kodfarki.subscreasy.client.model


/**
 * 
 * @param customerId 
 * @param selectedDate 
 * @param serviceUserId 
 */
data class InvoiceRequest (
    val customerId: kotlin.Long? = null,
    val selectedDate: java.time.LocalDateTime? = null,
    val serviceUserId: kotlin.Long? = null
) {

}

