/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.kodfarki.subscreasy.client.model


/**
 * 
 * @param amount 
 * @param billingMonth 
 * @param billingYear 
 * @param id 
 * @param periodEnd 
 * @param periodStart 
 * @param status 
 * @param subscriberSecureId 
 */
data class Invoice (
    val amount: java.math.BigDecimal? = null,
    val billingMonth: kotlin.Int? = null,
    val billingYear: kotlin.Int? = null,
    val id: kotlin.Long? = null,
    val periodEnd: java.time.LocalDateTime? = null,
    val periodStart: java.time.LocalDateTime? = null,
    val status: kotlin.String? = null,
    val subscriberSecureId: kotlin.String? = null
) {

}

