/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.kodfarki.subscreasy.client.model

import com.kodfarki.subscreasy.client.model.Company
import com.kodfarki.subscreasy.client.model.Subsription

/**
 * 
 * @param activityId 
 * @param company 
 * @param createDate 
 * @param detailProps 
 * @param details 
 * @param executionCount 
 * @param executionDate 
 * @param executionStatus 
 * @param firstExecutionDate 
 * @param id 
 * @param modifyDate 
 * @param priority 
 * @param retryDate 
 * @param retryRequired 
 * @param subscription 
 * @param workflowId 
 */
data class Job (
    val activityId: kotlin.Int? = null,
    val company: Company? = null,
    val createDate: java.time.LocalDateTime? = null,
    val detailProps: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,
    val details: kotlin.String? = null,
    val executionCount: kotlin.Int? = null,
    val executionDate: java.time.LocalDateTime? = null,
    val executionStatus: Job.ExecutionStatus? = null,
    val firstExecutionDate: java.time.LocalDateTime? = null,
    val id: kotlin.Long? = null,
    val modifyDate: java.time.LocalDateTime? = null,
    val priority: kotlin.Int? = null,
    val retryDate: java.time.LocalDateTime? = null,
    val retryRequired: kotlin.Boolean? = null,
    val subscription: Subsription? = null,
    val workflowId: Job.WorkflowId? = null
) {

    /**
    * 
    * Values: nEW,wAITING,rUNNING,pENDING,fINISHED,fAILED,cANCELLED,eXPIRED
    */
    enum class ExecutionStatus(val value: kotlin.Any){
    
        nEW("NEW"),
    
        wAITING("WAITING"),
    
        rUNNING("RUNNING"),
    
        pENDING("PENDING"),
    
        fINISHED("FINISHED"),
    
        fAILED("FAILED"),
    
        cANCELLED("CANCELLED"),
    
        eXPIRED("EXPIRED");
    
    }

    /**
    * 
    * Values: cHARGING,nOTIFY,tERMINATION,dAILY,oFFLINEPAYMENTCHECK
    */
    enum class WorkflowId(val value: kotlin.Any){
    
        cHARGING("CHARGING"),
    
        nOTIFY("NOTIFY"),
    
        tERMINATION("TERMINATION"),
    
        dAILY("DAILY"),
    
        oFFLINEPAYMENTCHECK("OFFLINE_PAYMENT_CHECK");
    
    }

}

