/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.kodfarki.subscreasy.client.model


/**
 * 
 * @param company 
 * @param password 
 * @param rememberMe 
 * @param username 
 */
data class LoginVM (
    val password: kotlin.String,
    val username: kotlin.String,
    val company: kotlin.String? = null,
    val rememberMe: kotlin.Boolean? = null
) {

}

