/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.kodfarki.subscreasy.client.model

import com.kodfarki.subscreasy.client.model.Company

/**
 * 
 * @param company 
 * @param enabled 
 * @param eventType 
 * @param id 
 * @param messageTemplate 
 * @param notificationType 
 * @param sender 
 * @param subject 
 */
data class MessageTemplate (
    val company: Company,
    val enabled: kotlin.Boolean? = null,
    val eventType: MessageTemplate.EventType? = null,
    val id: kotlin.Long? = null,
    val messageTemplate: kotlin.String? = null,
    val notificationType: MessageTemplate.NotificationType? = null,
    val sender: kotlin.String? = null,
    val subject: kotlin.String? = null
) {

    /**
    * 
    * Values: sTARTED,rENEWED,fINISHED,cANCELLED
    */
    enum class EventType(val value: kotlin.Any){
    
        sTARTED("STARTED"),
    
        rENEWED("RENEWED"),
    
        fINISHED("FINISHED"),
    
        cANCELLED("CANCELLED");
    
    }

    /**
    * 
    * Values: wEBHOOK,eMAIL
    */
    enum class NotificationType(val value: kotlin.Any){
    
        wEBHOOK("WEBHOOK"),
    
        eMAIL("EMAIL");
    
    }

}

