/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.kodfarki.subscreasy.client.model

import com.kodfarki.subscreasy.client.model.Company
import com.kodfarki.subscreasy.client.model.RecurrencePeriod

/**
 * 
 * @param company 
 * @param id 
 * @param name 
 * @param openEnded 
 * @param price 
 * @param recurrence 
 * @param recurrenceCount 
 * @param secureId 
 * @param trialPeriod 
 */
data class Offer (
    val company: Company,
    val name: kotlin.String,
    val openEnded: kotlin.Boolean,
    val price: java.math.BigDecimal,
    val recurrence: RecurrencePeriod,
    val id: kotlin.Long? = null,
    val recurrenceCount: kotlin.Int? = null,
    val secureId: kotlin.String? = null,
    val trialPeriod: kotlin.Int? = null
) {

}

