/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.kodfarki.subscreasy.client.model

import com.kodfarki.subscreasy.client.model.ChargingLog
import com.kodfarki.subscreasy.client.model.Company
import com.kodfarki.subscreasy.client.model.Offer
import com.kodfarki.subscreasy.client.model.Subscriber

/**
 * 
 * @param buyer 
 * @param company 
 * @param createDate 
 * @param id 
 * @param offer 
 * @param payment 
 * @param shippingAddress 
 * @param shippingCode 
 * @param shippingCompany 
 * @param status 
 * @param subscription 
 */
data class Order (
    val buyer: Subscriber,
    val company: Company,
    val offer: Offer,
    val status: Order.Status,
    val subscription: kotlin.Long,
    val createDate: java.time.LocalDateTime? = null,
    val id: kotlin.Long? = null,
    val payment: ChargingLog? = null,
    val shippingAddress: kotlin.Long? = null,
    val shippingCode: kotlin.String? = null,
    val shippingCompany: Order.ShippingCompany? = null
) {

    /**
    * 
    * Values: mNG,sURAT,yURTICI
    */
    enum class ShippingCompany(val value: kotlin.Any){
    
        mNG("MNG"),
    
        sURAT("SURAT"),
    
        yURTICI("YURTICI");
    
    }

    /**
    * 
    * Values: pREPARING,sHIPPED,dELIVERED,cANCELLED
    */
    enum class Status(val value: kotlin.Any){
    
        pREPARING("PREPARING"),
    
        sHIPPED("SHIPPED"),
    
        dELIVERED("DELIVERED"),
    
        cANCELLED("CANCELLED");
    
    }

}

