/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.kodfarki.subscreasy.client.model

import com.kodfarki.subscreasy.client.model.Offer
import com.kodfarki.subscreasy.client.model.Order
import com.kodfarki.subscreasy.client.model.Product

/**
 * 
 * @param id 
 * @param offer 
 * @param order 
 * @param product 
 * @param productCount 
 */
data class OrderItem (
    val id: kotlin.Long? = null,
    val offer: Offer? = null,
    val order: Order? = null,
    val product: Product? = null,
    val productCount: kotlin.Long? = null
) {

}

