/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.kodfarki.subscreasy.client.model


/**
 * 
 * @param cardAlias 
 * @param cardFamily 
 * @param cardHolderName 
 * @param cardNumber 
 * @param cardToken 
 * @param cardUserKey 
 * @param cvc 
 * @param expireMonth 
 * @param expireYear 
 * @param registerCard 
 */
data class PaymentCard (
    val cardAlias: kotlin.String? = null,
    val cardFamily: kotlin.String? = null,
    val cardHolderName: kotlin.String? = null,
    val cardNumber: kotlin.String? = null,
    val cardToken: kotlin.String? = null,
    val cardUserKey: kotlin.String? = null,
    val cvc: kotlin.String? = null,
    val expireMonth: kotlin.String? = null,
    val expireYear: kotlin.String? = null,
    val registerCard: kotlin.Int? = null
) {

}

