/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.kodfarki.subscreasy.client.model

import com.kodfarki.subscreasy.client.model.Company
import com.kodfarki.subscreasy.client.model.Offer

/**
 * 
 * @param company 
 * @param description 
 * @param id 
 * @param name 
 * @param offers 
 * @param productType 
 */
data class Product (
    val company: Company,
    val description: kotlin.String,
    val name: kotlin.String,
    val id: kotlin.Long? = null,
    val offers: kotlin.Array<Offer>? = null,
    val productType: Product.ProductType? = null
) {

    /**
    * 
    * Values: sERVICE,pHYSICAL
    */
    enum class ProductType(val value: kotlin.Any){
    
        sERVICE("SERVICE"),
    
        pHYSICAL("PHYSICAL");
    
    }

}

