/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.kodfarki.subscreasy.client.model


/**
 * 
 * @param activeProfiles 
 * @param ribbonEnv 
 * @param version 
 */
data class ProfileInfoVM (
    val activeProfiles: kotlin.Array<kotlin.String>? = null,
    val ribbonEnv: kotlin.String? = null,
    val version: kotlin.String? = null
) {

}

