/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.kodfarki.subscreasy.client.model


/**
 * 
 * @param binNumber 
 * @param cardAlias 
 * @param cardAssociation 
 * @param cardBankCode 
 * @param cardBankName 
 * @param cardFamily 
 * @param cardToken 
 * @param cardUserKey 
 * @param cartType 
 * @param id 
 */
data class SavedCard (
    val binNumber: kotlin.String? = null,
    val cardAlias: kotlin.String? = null,
    val cardAssociation: kotlin.String? = null,
    val cardBankCode: kotlin.Long? = null,
    val cardBankName: kotlin.String? = null,
    val cardFamily: kotlin.String? = null,
    val cardToken: kotlin.String? = null,
    val cardUserKey: kotlin.String? = null,
    val cartType: kotlin.String? = null,
    val id: kotlin.Long? = null
) {

}

