/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.kodfarki.subscreasy.client.model

import com.kodfarki.subscreasy.client.model.PaymentCard
import com.kodfarki.subscreasy.client.model.Subscriber
import com.kodfarki.subscreasy.client.model.Subsription

/**
 * 
 * @param paymentCard 
 * @param subscriber 
 * @param subscription 
 */
data class SaveCardRequest (
    val paymentCard: PaymentCard? = null,
    val subscriber: Subscriber? = null,
    val subscription: Subsription? = null
) {

}

