/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.kodfarki.subscreasy.client.model

import com.kodfarki.subscreasy.client.model.Company
import com.kodfarki.subscreasy.client.model.Offer
import com.kodfarki.subscreasy.client.model.Service

/**
 * 
 * @param company 
 * @param description 
 * @param id 
 * @param offer 
 * @param overUsagePrice 
 * @param overUsageQuota 
 * @param price 
 * @param quotaAmount 
 * @param service 
 * @param unitName 
 */
data class ServiceOffering (
    val offer: Offer,
    val quotaAmount: java.math.BigDecimal,
    val company: Company? = null,
    val description: kotlin.String? = null,
    val id: kotlin.Long? = null,
    val overUsagePrice: java.math.BigDecimal? = null,
    val overUsageQuota: java.math.BigDecimal? = null,
    val price: java.math.BigDecimal? = null,
    val service: Service? = null,
    val unitName: kotlin.String? = null
) {

}

