/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.kodfarki.subscreasy.client.model


/**
 * 
 * @param capacity 
 * @param id 
 * @param name 
 * @param price 
 * @param type 
 * @param unitName 
 * @param unitsPerPrice 
 */
data class ServiceOfferingResult (
    val capacity: kotlin.String? = null,
    val id: kotlin.Long? = null,
    val name: kotlin.String? = null,
    val price: java.math.BigDecimal? = null,
    val type: kotlin.String? = null,
    val unitName: kotlin.String? = null,
    val unitsPerPrice: java.math.BigDecimal? = null
) {

}

