/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.kodfarki.subscreasy.client.model

import com.kodfarki.subscreasy.client.model.Offer
import com.kodfarki.subscreasy.client.model.ServiceOffering
import com.kodfarki.subscreasy.client.model.Subsription

/**
 * 
 * @param capacity 
 * @param currentUsage 
 * @param endDate 
 * @param id 
 * @param name 
 * @param numberOfUnits 
 * @param offer 
 * @param overUsage 
 * @param overUsageQuota 
 * @param quotaOrigin 
 * @param serviceOffering 
 * @param serviceType 
 * @param startDate 
 * @param status 
 * @param subscriberId 
 * @param subscription 
 * @param type 
 * @param version 
 */
data class ServiceInstance (
    val capacity: java.math.BigDecimal? = null,
    val currentUsage: java.math.BigDecimal? = null,
    val endDate: java.time.LocalDateTime? = null,
    val id: kotlin.Long? = null,
    val name: kotlin.String? = null,
    val numberOfUnits: kotlin.Int? = null,
    val offer: Offer? = null,
    val overUsage: java.math.BigDecimal? = null,
    val overUsageQuota: java.math.BigDecimal? = null,
    val quotaOrigin: ServiceInstance.QuotaOrigin? = null,
    val serviceOffering: ServiceOffering? = null,
    val serviceType: ServiceInstance.ServiceType? = null,
    val startDate: java.time.LocalDateTime? = null,
    val status: ServiceInstance.Status? = null,
    val subscriberId: kotlin.String? = null,
    val subscription: Subsription? = null,
    val type: ServiceInstance.Type? = null,
    val version: kotlin.Long? = null
) {

    /**
    * 
    * Values: sUBS,oVER
    */
    enum class QuotaOrigin(val value: kotlin.Any){
    
        sUBS("SUBS"),
    
        oVER("OVER");
    
    }

    /**
    * 
    * Values: oNOFF,sEATBASED,uSAGEBASED
    */
    enum class ServiceType(val value: kotlin.Any){
    
        oNOFF("ONOFF"),
    
        sEATBASED("SEAT_BASED"),
    
        uSAGEBASED("USAGE_BASED");
    
    }

    /**
    * 
    * Values: nEW,aCTIVE,sUSPENDED,fINISHED,cANCELLED
    */
    enum class Status(val value: kotlin.Any){
    
        nEW("NEW"),
    
        aCTIVE("ACTIVE"),
    
        sUSPENDED("SUSPENDED"),
    
        fINISHED("FINISHED"),
    
        cANCELLED("CANCELLED");
    
    }

    /**
    * 
    * Values: oNOFF,sEATBASED,uSAGEBASED
    */
    enum class Type(val value: kotlin.Any){
    
        oNOFF("ONOFF"),
    
        sEATBASED("SEAT_BASED"),
    
        uSAGEBASED("USAGE_BASED");
    
    }

}

