/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.kodfarki.subscreasy.client.model


/**
 * 
 * @param capacity 
 * @param endDate 
 * @param id 
 * @param name 
 * @param overUsage 
 * @param type 
 * @param usage 
 */
data class ServiceInstanceResult (
    val capacity: java.math.BigDecimal? = null,
    val endDate: java.time.LocalDateTime? = null,
    val id: kotlin.Long? = null,
    val name: kotlin.String? = null,
    val overUsage: java.math.BigDecimal? = null,
    val type: kotlin.String? = null,
    val usage: java.math.BigDecimal? = null
) {

}

