/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.kodfarki.subscreasy.client.model

import com.kodfarki.subscreasy.client.model.Company

/**
 * 
 * @param company 
 * @param id 
 * @param name 
 * @param type 
 */
data class Service (
    val company: Company,
    val name: kotlin.String,
    val type: Service.Type,
    val id: kotlin.Long? = null
) {

    /**
    * 
    * Values: oNOFF,sEATBASED,uSAGEBASED
    */
    enum class Type(val value: kotlin.Any){
    
        oNOFF("ONOFF"),
    
        sEATBASED("SEAT_BASED"),
    
        uSAGEBASED("USAGE_BASED");
    
    }

}

