/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.kodfarki.subscreasy.client.model

import com.kodfarki.subscreasy.client.model.PaymentCard
import com.kodfarki.subscreasy.client.model.Subscriber
import com.kodfarki.subscreasy.client.model.SubscriptionPlan

/**
 * 
 * @param apiKey 
 * @param callbackUrl 
 * @param couponCode 
 * @param offer 
 * @param paymentCard 
 * @param subscriber 
 */
data class StartSubscriptionRequest (
    val apiKey: kotlin.String? = null,
    val callbackUrl: kotlin.String? = null,
    val couponCode: kotlin.String? = null,
    val offer: SubscriptionPlan? = null,
    val paymentCard: PaymentCard? = null,
    val subscriber: Subscriber? = null
) {

}

