/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.kodfarki.subscreasy.client.model


/**
 * 
 * @param address 
 * @param city 
 * @param country 
 * @param email 
 * @param gsmNumber 
 * @param identityNumber 
 * @param ip 
 * @param lastLoginDate 
 * @param name 
 * @param registrationDate 
 * @param secureId 
 * @param shippingAddress 
 * @param shippingCity 
 * @param shippingCountry 
 * @param shippingName 
 * @param shippingZipCode 
 * @param surname 
 * @param useBillingAddressForShipping 
 * @param zipCode 
 */
data class Subscriber (
    val address: kotlin.String? = null,
    val city: kotlin.String? = null,
    val country: kotlin.String? = null,
    val email: kotlin.String? = null,
    val gsmNumber: kotlin.String? = null,
    val identityNumber: kotlin.String? = null,
    val ip: kotlin.String? = null,
    val lastLoginDate: kotlin.String? = null,
    val name: kotlin.String? = null,
    val registrationDate: kotlin.String? = null,
    val secureId: kotlin.String? = null,
    val shippingAddress: kotlin.String? = null,
    val shippingCity: kotlin.String? = null,
    val shippingCountry: kotlin.String? = null,
    val shippingName: kotlin.String? = null,
    val shippingZipCode: kotlin.String? = null,
    val surname: kotlin.String? = null,
    val useBillingAddressForShipping: kotlin.Boolean? = null,
    val zipCode: kotlin.String? = null
) {

}

