/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.kodfarki.subscreasy.client.model

import com.kodfarki.subscreasy.client.model.Address
import com.kodfarki.subscreasy.client.model.Company

/**
 * 
 * @param billingAddress 
 * @param company 
 * @param createDate 
 * @param email 
 * @param id 
 * @param identificationNo 
 * @param merchantSubscriberId 
 * @param name 
 * @param phoneNumber 
 * @param secureId 
 * @param shippingAddress 
 * @param surname 
 * @param taxAdministration 
 * @param taxNumber 
 * @param worksFor 
 */
data class Subscriber (
    val billingAddress: Address? = null,
    val company: Company? = null,
    val createDate: java.time.LocalDateTime? = null,
    val email: kotlin.String? = null,
    val id: kotlin.Long? = null,
    val identificationNo: kotlin.String? = null,
    val merchantSubscriberId: kotlin.String? = null,
    val name: kotlin.String? = null,
    val phoneNumber: kotlin.String? = null,
    val secureId: kotlin.String? = null,
    val shippingAddress: Address? = null,
    val surname: kotlin.String? = null,
    val taxAdministration: kotlin.String? = null,
    val taxNumber: kotlin.String? = null,
    val worksFor: kotlin.String? = null
) {

}

