/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.kodfarki.subscreasy.client.model

import com.kodfarki.subscreasy.client.model.Company
import com.kodfarki.subscreasy.client.model.Coupon
import com.kodfarki.subscreasy.client.model.Offer
import com.kodfarki.subscreasy.client.model.SavedCard
import com.kodfarki.subscreasy.client.model.ServiceInstance

/**
 * 
 * @param appliedCoupon 
 * @param cancelDate 
 * @param card 
 * @param company 
 * @param endDate 
 * @param id 
 * @param nextChargingDate 
 * @param offer 
 * @param services 
 * @param startDate 
 * @param status 
 * @param subscriberId 
 * @param version 
 */
data class Subsription (
    val company: Company,
    val offer: Offer,
    val appliedCoupon: Coupon? = null,
    val cancelDate: java.time.LocalDateTime? = null,
    val card: SavedCard? = null,
    val endDate: java.time.LocalDateTime? = null,
    val id: kotlin.Long? = null,
    val nextChargingDate: java.time.LocalDateTime? = null,
    val services: kotlin.Array<ServiceInstance>? = null,
    val startDate: java.time.LocalDateTime? = null,
    val status: Subsription.Status? = null,
    val subscriberId: kotlin.String? = null,
    val version: kotlin.Long? = null
) {

    /**
    * 
    * Values: nEW,aCTIVE,sUSPENDED,fINISHED,cANCELLED
    */
    enum class Status(val value: kotlin.Any){
    
        nEW("NEW"),
    
        aCTIVE("ACTIVE"),
    
        sUSPENDED("SUSPENDED"),
    
        fINISHED("FINISHED"),
    
        cANCELLED("CANCELLED");
    
    }

}

