/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.kodfarki.subscreasy.client.model

import com.kodfarki.subscreasy.client.model.Company
import com.kodfarki.subscreasy.client.model.Coupon
import com.kodfarki.subscreasy.client.model.Offer
import com.kodfarki.subscreasy.client.model.SavedCard
import com.kodfarki.subscreasy.client.model.ServiceInstance
import com.kodfarki.subscreasy.client.model.Subscriber

/**
 * 
 * @param appliedCoupon 
 * @param cancelDate 
 * @param card 
 * @param company 
 * @param endDate 
 * @param id 
 * @param lastEvent 
 * @param offer 
 * @param paymentMethod 
 * @param services 
 * @param startDate 
 * @param status 
 * @param subscriber 
 * @param subscriberSecureId 
 * @param termEndDate 
 * @param termStartDate 
 * @param trialEndDate 
 */
data class Subsription (
    val company: Company,
    val offer: Offer,
    val appliedCoupon: Coupon? = null,
    val cancelDate: java.time.LocalDateTime? = null,
    val card: SavedCard? = null,
    val endDate: java.time.LocalDateTime? = null,
    val id: kotlin.Long? = null,
    val lastEvent: Subsription.LastEvent? = null,
    val paymentMethod: Subsription.PaymentMethod? = null,
    val services: kotlin.Array<ServiceInstance>? = null,
    val startDate: java.time.LocalDateTime? = null,
    val status: Subsription.Status? = null,
    val subscriber: Subscriber? = null,
    val subscriberSecureId: kotlin.String? = null,
    val termEndDate: java.time.LocalDateTime? = null,
    val termStartDate: java.time.LocalDateTime? = null,
    val trialEndDate: java.time.LocalDateTime? = null
) {

    /**
    * 
    * Values: sTARTED,rENEWED,rENEWALFAILED,fINISHED,cANCELLED,sUBSCRIBERCREATED,sUBSCRIBERUPDATED,tRIALENDING,pAYMENTUPDATED,iMMEDIATECANCELLATIONREQUESTED,eNDOFPERIODCANCELLATIONREQUESTED,pRICEUPDATED
    */
    enum class LastEvent(val value: kotlin.Any){
    
        sTARTED("STARTED"),
    
        rENEWED("RENEWED"),
    
        rENEWALFAILED("RENEWAL_FAILED"),
    
        fINISHED("FINISHED"),
    
        cANCELLED("CANCELLED"),
    
        sUBSCRIBERCREATED("SUBSCRIBER_CREATED"),
    
        sUBSCRIBERUPDATED("SUBSCRIBER_UPDATED"),
    
        tRIALENDING("TRIAL_ENDING"),
    
        pAYMENTUPDATED("PAYMENT_UPDATED"),
    
        iMMEDIATECANCELLATIONREQUESTED("IMMEDIATE_CANCELLATION_REQUESTED"),
    
        eNDOFPERIODCANCELLATIONREQUESTED("ENDOFPERIOD_CANCELLATION_REQUESTED"),
    
        pRICEUPDATED("PRICE_UPDATED");
    
    }

    /**
    * 
    * Values: oFFLINE,cC,mOBILE
    */
    enum class PaymentMethod(val value: kotlin.Any){
    
        oFFLINE("OFFLINE"),
    
        cC("CC"),
    
        mOBILE("MOBILE");
    
    }

    /**
    * 
    * Values: nEW,aCTIVE,sUSPENDED,fINISHED,cANCELLED,iNTRIAL,pAYMENTDUE
    */
    enum class Status(val value: kotlin.Any){
    
        nEW("NEW"),
    
        aCTIVE("ACTIVE"),
    
        sUSPENDED("SUSPENDED"),
    
        fINISHED("FINISHED"),
    
        cANCELLED("CANCELLED"),
    
        iNTRIAL("IN_TRIAL"),
    
        pAYMENTDUE("PAYMENT_DUE");
    
    }

}

