/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.kodfarki.subscreasy.client.model

import com.kodfarki.subscreasy.client.model.Company

/**
 * 
 * @param authenticationKey 
 * @param company 
 * @param id 
 * @param paymentUpdated 
 * @param serverUrl 
 * @param subscriberCreated 
 * @param subscriberUpdated 
 * @param subscriptionCreated 
 * @param subscriptionEnded 
 * @param subscriptionReactivated 
 * @param subscriptionRenewalFailed 
 * @param subscriptionRenewed 
 */
data class WebHook (
    val authenticationKey: kotlin.String? = null,
    val company: Company? = null,
    val id: kotlin.Long? = null,
    val paymentUpdated: kotlin.Boolean? = null,
    val serverUrl: kotlin.String? = null,
    val subscriberCreated: kotlin.Boolean? = null,
    val subscriberUpdated: kotlin.Boolean? = null,
    val subscriptionCreated: kotlin.Boolean? = null,
    val subscriptionEnded: kotlin.Boolean? = null,
    val subscriptionReactivated: kotlin.Boolean? = null,
    val subscriptionRenewalFailed: kotlin.Boolean? = null,
    val subscriptionRenewed: kotlin.Boolean? = null
) {

}

